Tweak UI styling
google/triage-party pull request #233
Opened 2020-11-06 13:56 UTC by davkal

I find the existing UI hard to read. It's good at showing a lot info at high density, but I find that distracting when going through issues (sometimes even via screen sharing). I propose a lighter touch, less dense and more readable. 

- keep main color theme based on Vivid and Sharp: https://visme.co/blog/website-color-schemes/
- remove lots of custom styles and embrace Bulma panel and table styles
- updates Bulma from 0.75 to 0.9
- remove datatable-specific styling

Before: 
![Screenshot 2020-11-06 at 14 53 05](https://user-images.githubusercontent.com/859729/98373789-0e9b8100-2040-11eb-82e6-880d8e5f5a2c.png)

After:
![Screenshot 2020-11-06 at 14 52 30](https://user-images.githubusercontent.com/859729/98373804-12c79e80-2040-11eb-9883-801cee048e65.png)

2020-11-13 10:35 UTC, davkal commented
The design is just a straw-person really, I do wonder if others share the issues I'm having. FWIW, I've been using triage party more heavily now, and have gotten used to the existing style.

2021-01-15 17:57 UTC, tstromberg requested changes
I like the changes you've proposed, and would like to see this get merged if possible as an improvement over the current iteration.

2021-01-15 17:57 UTC, tstromberg commented on site/base.tmpl
> +    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
Can you bring the updated bulma into the /third_party directory?

2021-02-23 01:28 UTC, tstromberg commented
Closing until this can be revisited.

2021-02-23 01:28 UTC, closed without merging